project_id = "fltbaxdcpoapajlymiou"

[functions.generate-image]
verify_jwt = false

[functions.upload-image]
verify_jwt = false

[functions.improve-prompt]
verify_jwt = false

[functions.extract-style]
verify_jwt = false
